/** Declaration file generated by dts-gen */

export function dft(vector: any): any;

export function fft(vector: any): any;

export function fftInPlace(vector: any): void;

export function idft(signal: any): any;

export function ifft(signal: any): any;

export namespace util {
    function exponent(k: any, N: any): any;

    function fftFreq(fftBins: any, sampleRate: any): any;

    function fftMag(fftBins: any): any;

}

