/** Declaration file generated by dts-gen */

export = ooura;

declare class ooura {
    constructor(...args: any[]);

    fftComplex(...args: any[]): void;

    fft(...args: any[]): void;

    fftInPlaceComplex(...args: any[]): void;

    fftInPlaceReal(...args: any[]): void;

    fftReal(...args: any[]): void;

    getScalarSize(...args: any[]): void;

    getVectorSize(...args: any[]): void;

    ifftComplex(...args: any[]): void;

    ifftInPlaceComplex(...args: any[]): void;

    ifftInPlaceReal(...args: any[]): void;

    ifftReal(...args: any[]): void;

    scalarArrayFactory(...args: any[]): void;

    vectorArrayFactory(...args: any[]): Float64Array;

    xfftComplex(...args: any[]): void;

    static isPowerOf2(...args: any[]): void;

    static scalarSize(...args: any[]): void;

    static vectorSize(...args: any[]): void;

}

